(define-read-only (get-helper-22) (ok u22))
(define-read-only (ping-44) (ok true))
(define-read-only (get-helper-106) (ok u106))
(define-read-only (ping-131) (ok true))
(define-read-only (ping-139) (ok true))
