(define-read-only (get-helper-7) (ok u7))
(define-read-only (ping-8) (ok true))
(define-read-only (get-helper-13) (ok u13))
(define-read-only (get-helper-36) (ok u36))
(define-read-only (ping-47) (ok true))
